name: Build Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2
        
      - name: Setup jdk 21
        uses: actions/setup-java@v3.14.1
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Grant execution permission to gradlew
        run: chmod +x ./gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run detekt
        run: ./gradlew detekt

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      
      - name: Build and push ai-service
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ai-service:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ai-service:${{ github.sha }}
          build-args: |
            MODULE=ai-service

      - name: Build and push api-gateway
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api-gateway:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api-gateway:${{ github.sha }}
          build-args: |
            MODULE=api-gateway

      - name: Build and push authentication-service
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-authentication-service:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-authentication-service:${{ github.sha }}
          build-args: |
            MODULE=authentication-service

      - name: Build and push config-server
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-config-server:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-config-server:${{ github.sha }}
          build-args: |
            MODULE=config-server

      - name: Build and push discovery-server
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-discovery-server:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-discovery-server:${{ github.sha }}
          build-args: |
            MODULE=discovery-server

      - name: Build and push media-service
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-media-service:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-media-service:${{ github.sha }}
          build-args: |
            MODULE=media-service

      - name: Build and push note-service
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-note-service:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-note-service:${{ github.sha }}
          build-args: |
            MODULE=note-service

      - name: Build and push user-service
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-user-service:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-user-service:${{ github.sha }}
          build-args: |
            MODULE=user-service

      - name: Deploy
        run: echo "deploying..."
